GET http://localhost:4000/
###
GET http://localhost:4000/auth

###
GET http://localhost:4000/posts


###

POST http://localhost:000/auth/signup
Content-Type: application/json

{
    "username": "test1",
    "password": "test1"
}


###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "test1",
    "password": "test1"
}

###
POST http://localhost:4000/posts/create
Content-Type: application/json

{
    "title": "post2",
    "authorId": "placeholder",
    "commentId": "placeholder",
    "message": "post2",
    "likes": "[]"
    
}


###
GET http://localhost:4000/posts


###
GET http://localhost:4000/comments
Content-Type: application/json

{
    "postId": "636e94d872a6e98ed806603e"
}

###
POST http://localhost:4000/comments/send
Content-Type: application/json

{
    "text": "test1",
    "authorId": "test1",
    "postId": "test1"
}


###

GET http://localhost:4000/posts/6376637b79631bd3c800f19c/likes

###

POST http://localhost:4000/profile/create/636c187091bda9498a3f5a20
Content-Type: application/json

{
    "userId": "636c187091bda9498a3f5a20",
    "age":13,
    "gender":"male",
    "worstTravelExp":"chicago",
    "designTVShow": "doctor who",
    "superpower":"fly"
   
}

###
GET http://localhost:4000/profile/create/636c187091bda9498a3f5a20


###

GET http://localhost:4000/friends/pending

###
POST http://localhost:4000/friends/pending


###
GET http://localhost:4000/friends/accepted
###

POST http://localhost:4000/friends/accepted

/////////////////////////////////////////////////////
/////////////////////////////////////////////////////
////////SEPTEMBER 2023 REWORKING PROJECT/////////////
/////////////////////////////////////////////////////
/////////////////////////////////////////////////////

//Update a comment
###
PUT http://localhost:4000/comments/123

// Delete a comment
###
DELETE http://localhost:4000/comments/123


//Update a specific post
###
PUT http://localhost:4000/posts/123

//Delete a specific post
###
DELETE http://localhost:4000/posts/123
