GET http://localhost:4000/

###
GET http://localhost:4000/posts


###

POST http://localhost:000/auth/signup
Content-Type: application/json

{
    "username": "test1",
    "password": "test1"
}


###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "test1",
    "password": "test1"
}

###
POST http://localhost:4000/posts/create
Content-Type: application/json

{
    "title": "post1",
    "authorId": "placeholder",
    "commentId": "placeholder",
    "message": "post1",
    "likes": "[]"
    
}