GET http://localhost:4000/
###
GET http://localhost:4000/auth

###
GET http://localhost:4000/posts


###

POST http://localhost:000/auth/signup
Content-Type: application/json

{
    "username": "test1",
    "password": "test1"
}


###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "test1",
    "password": "test1"
}

###
POST http://localhost:4000/posts/create
Content-Type: application/json

{
    "title": "post2",
    "authorId": "placeholder",
    "commentId": "placeholder",
    "message": "post2",
    "likes": "[]"
    
}


###
GET http://localhost:4000/posts


###
GET http://localhost:4000/comments
Content-Type: application/json

{
    "postId": "636e94d872a6e98ed806603e"
}

###
POST http://localhost:4000/comments/send
Content-Type: application/json

{
    "text": "test1",
    "authorId": "test1",
    "postId": "test1"
}


###

GET http://localhost:4000/posts/6376637b79631bd3c800f19c/likes

###

POST http://localhost:4000/profile/create/636c187091bda9498a3f5a20
Content-Type: application/json

{
    "userId": "636c187091bda9498a3f5a20",
    "age":13,
    "gender":"male",
    "worstTravelExp":"chicago",
    "designTVShow": "doctor who",
    "superpower":"fly"
   
}

###
GET http://localhost:4000/profile/create/636c187091bda9498a3f5a20


###

GET http://localhost:4000/friends/pending

###
POST http://localhost:4000/friends/pending


###
GET http://localhost:4000/friends/accepted
###

POST http://localhost:4000/friends/accepted

/////////////////////////////////////////////////////
/////////////////////////////////////////////////////
////////SEPTEMBER 2023 REWORKING PROJECT/////////////
/////////////////////////////////////////////////////
/////////////////////////////////////////////////////


///////////// Testing COMMENTS functionalities
//Update a comment
###
PUT http://localhost:4000/comments/123

// Delete a comment
###
DELETE http://localhost:4000/comments/123

///////////// Testing Post (actual posts made by users) functionalities
//Update a specific post
###
PATCH http://localhost:4000/posts/6376637b79631bd3c800f19c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMSIsImlhdCI6MTY4OTI4MjA3NX0.z7wy1gMBvDDMGR9ob74oucY6yYintfK206JWd8YYBzw
Content-Type: application/json

{
    "title": "new title"
}
//Delete a specific post
###
DELETE http://localhost:4000/posts/650ccbdc6c38c68a1d0ce978
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMSIsImlhdCI6MTY4OTI4MjA3NX0.z7wy1gMBvDDMGR9ob74oucY6yYintfK206JWd8YYBzw


###
GET http://localhost:4000/posts

###
DELETE http://localhost:4000/comments/63766119c8708f8170062f72
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMSIsImlhdCI6MTY4OTI4MjA3NX0.z7wy1gMBvDDMGR9ob74oucY6yYintfK206JWd8YYBzw


/////////////////// Testing LIKES functionalities
//Adding a like 
###
POST http://localhost:4000/posts/650b24d0825e551ccf70ed32/likes
Content-Type: application/json

{
    "userId": "test5"
}
###
//get likes 
GET http://localhost:4000/posts/650b24d0825e551ccf70ed32/likes

//Unlike functionality
###
POST http://localhost:4000/posts/650b24d0825e551ccf70ed32/unlike
Content-Type: application/json

{
    "userId": "test1"
}

//likes -> 650128b1fa256bb871fb51ac / test1 /test2 


///////////// Testing FRIENDS SYSTEM functionalities
###
//Get all pending friend requests
GET http://localhost:4000/friends/pending/650c78b847d9e8e3b9cbfa4d

###
//Get all friends
GET http://localhost:4000/friends/accepted/650c78b847d9e8e3b9cbfa4d